Fixing more craziness

diff --git a/scripts/pbuilder/build-sources b/scripts/pbuilder/build-sources
--- a/scripts/pbuilder/build-sources
+++ b/scripts/pbuilder/build-sources
@@ -9,14 +9,16 @@ cd $PKG_PATH
 echo "--------------------------------"
 echo "Installing build-dependencies..."
 
-mk-build-deps -i -r -t "apt-get --no-install-recommends -y" || exit 1
+LOG="/var/log/mk-build-deps.log"
+mk-build-deps -i -t "apt-get --no-install-recommends -y" >> $LOG 2>&1 \
+  || { echo "mk-build-deps failed, logs are in $LOG"; exit 1; }
 rm -f *build-deps*_all.deb
 
 echo "--------------------------------"
 echo "Creating source package..."
 
 # Creating source package without signing it
-debuild -S -sa -uc
+debuild -S -sa -uc --no-lintian
 
 # Be sure to clean directory
 debclean
diff --git a/scripts/rebuildd/upload-binaries b/scripts/rebuildd/upload-binaries
--- a/scripts/rebuildd/upload-binaries
+++ b/scripts/rebuildd/upload-binaries
@@ -29,40 +29,26 @@ get_source_component() {
         listfilter $CODENAME "\$Source (==${package}), \$SourceVersion (==${version})"
 }
 COMPONENT=$(get_source_component)
-if [ -z "$COMPONENT" ]; then
-    echo "Unable to retrieve source package component"
-    exit 1
-fi
+[ -n "$COMPONENT" ] || echo "Unable to retrieve source package component"
 
 echo "#########################"
 echo " Adding binary package..."
 echo "#########################"
 
-include_to() {
-    # Include changes to the given repo (waiting 1m max)
-    echo "Adding to ${1}/$COMPONENT..."
-    reprepro --waitforlock 6 -b $REPO_DIR -C $COMPONENT include $1 \
-        $CHANGES_FILE > /dev/null 1>&1 || return 1
-}
+# Include changes to the given repo (waiting 1m max)
+echo "Adding to $CODENAME/$COMPONENT..."
 
-if include_to $CODENAME ; then
-    status=0
-else
-    status=1
-fi
+reprepro --waitforlock 6 -b $REPO_DIR -C $COMPONENT include $CODENAME $CHANGES_FILE > /dev/null
 
+status=$?
 if [ $status -eq 0 ]; then
     # Clean pbuilder results
     for f in $(get_files $CHANGES_FILE); do
         rm -f /var/cache/pbuilder/result/$f
     done
+    sendxmpppy "Completed build of ${package}/${version} for ${CODENAME}/${COMPONENT}/${arch}."
+else
+    sendxmpppy "Failed to include change of ${package}/${version} for ${CODENAME}/${COMPONENT}/${arch} ?!"
 fi
-
-
-# Send notification on xmpp dev room
-
-export HOME=$HOME_PBUILDER
-
-sendxmpppy "Completed build of ${package}/${version} for ${CODENAME}/${COMPONENT}/${arch}."
 
 exit $status
